# Interface/visualizer.py
import streamlit as st

def display_results(report: dict):
    # ... (the image display part is the same)
    st.subheader("Analysis Results")
    col1, col2, col3 = st.columns(3)
    with col1:
        st.image(report['images']['before'], caption="Before", use_column_width=True)
    with col2:
        st.image(report['images']['after'], caption="After", use_column_width=True)
    with col3:
        st.image(report['images']['difference'], caption="Change Detected", use_column_width=True)
        
    st.markdown("---")
    st.subheader("Event Classification")
    analysis = report['analysis']
    st.metric(label="Detected Event", value=analysis['event_class'])
    st.progress(analysis['confidence'], text=f"Confidence: {analysis['confidence']:.0%}")
    st.info(analysis['summary'])
    
    st.markdown("---")
    st.subheader("Proposed Solutions (Generated by RAG)")
    # --- CHANGE: Display the raw text from the RAG chain ---
    st.markdown(report['solutions'])